### DataFrame 의 행, 열 인덱스

In [1]:
import pandas as pd

In [2]:
sample = pd.read_csv("내국인 생활인구.csv", encoding="cp949")

# 한글이 포함되어 있으면 제대로 못불러 올 수 있기 때문에 encoding='cp949' 를 넣어주자.

In [3]:
sample

,일자(stdr_de_id),시간(tmzon_pd_se),행정동코드(adstrd_code_se),집계구코드(oa_cd),생활인구합계(tot_lvpop_co),남자0~9세(male_f0t9_lvpop_co),남자10~14세(male_f10t14_lvpop_co),남자15~19세(male_f15t19_lvpop_co),남자20~24세(male_f20t24_lvpop_co),남자25~29세(male_f25t29_lvpop_co),...,여자40~44세(female_f40t44_lvpop_co),여자45~49세(female_f45t49_lvpop_co),여자50~54세(female_f50t54_lvpop_co),여자55~59세(female_f55t59_lvpop_co),여자60~64세(female_f60t64_lvpop_co),여자65~69세(female_f65t69_lvpop_co),여자70~74세(female_f70t74_lvpop_co),여자75~79세(female_f75t79_lvpop_co),여자80세이상(female_above_80_lvpop_co),등록일자(ldadng_dt)
0,20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
1,20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
2,20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
3,20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
4,20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,20170603,7,11650560,1122057010104,465.8914,16.4274,4.2056,11.2869,3.5184,14.1803,...,17.2636,4.9406,16.3334,26.8672,1.0048,3.5458,18.9442,13.5570,17.3543,2021-08-17 16:06:44
496,20211007,5,11620525,1111056061002,180.1291,12.6887,8.1278,2.1684,23.3810,5.5894,...,9.7934,23.8109,10.2240,28.3686,9.9961,7.2371,5.7134,15.6473,6.1426,2021-08-17 16:06:44
497,20200819,20,11140635,1121078010101,540.8267,0.7004,14.3413,2.9791,0.2832,13.5837,...,0.0017,13.7260,14.1506,46.9632,10.5080,8.6825,3.9238,3.3179,13.5500,2021-08-17 16:06:44
498,20171011,11,11590605,1121082010004,992.2594,35.4771,8.4071,17.8773,1.2632,1.8164,...,3.9551,28.8403,10.7913,33.7729,1.4717,8.7947,8.5835,9.3403,0.0000,2021-08-17 16:06:44
499,20200725,21,11350625,1115053030001,1098.0798,12.6300,12.6652,18.6522,275.4479,20.0665,...,63.2687,18.9043,36.0630,27.1679,18.4721,13.1369,21.8967,6.0132,4.8362,2021-08-17 16:06:44

**head**, **tail** 함수 데이터가 너무 많으면, 오히려 보기 불편할 수도.

데이터 생김새만 보고 싶으면 맨위 또는 맨 아래 n 개만 볼 수 있는 기능

In [4]:
sample.head()

,일자(stdr_de_id),시간(tmzon_pd_se),행정동코드(adstrd_code_se),집계구코드(oa_cd),생활인구합계(tot_lvpop_co),남자0~9세(male_f0t9_lvpop_co),남자10~14세(male_f10t14_lvpop_co),남자15~19세(male_f15t19_lvpop_co),남자20~24세(male_f20t24_lvpop_co),남자25~29세(male_f25t29_lvpop_co),...,여자40~44세(female_f40t44_lvpop_co),여자45~49세(female_f45t49_lvpop_co),여자50~54세(female_f50t54_lvpop_co),여자55~59세(female_f55t59_lvpop_co),여자60~64세(female_f60t64_lvpop_co),여자65~69세(female_f65t69_lvpop_co),여자70~74세(female_f70t74_lvpop_co),여자75~79세(female_f75t79_lvpop_co),여자80세이상(female_above_80_lvpop_co),등록일자(ldadng_dt)
0,20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
1,20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
2,20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
3,20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
4,20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44

In [5]:
sample.tail()

,일자(stdr_de_id),시간(tmzon_pd_se),행정동코드(adstrd_code_se),집계구코드(oa_cd),생활인구합계(tot_lvpop_co),남자0~9세(male_f0t9_lvpop_co),남자10~14세(male_f10t14_lvpop_co),남자15~19세(male_f15t19_lvpop_co),남자20~24세(male_f20t24_lvpop_co),남자25~29세(male_f25t29_lvpop_co),...,여자40~44세(female_f40t44_lvpop_co),여자45~49세(female_f45t49_lvpop_co),여자50~54세(female_f50t54_lvpop_co),여자55~59세(female_f55t59_lvpop_co),여자60~64세(female_f60t64_lvpop_co),여자65~69세(female_f65t69_lvpop_co),여자70~74세(female_f70t74_lvpop_co),여자75~79세(female_f75t79_lvpop_co),여자80세이상(female_above_80_lvpop_co),등록일자(ldadng_dt)
495,20170603,7,11650560,1122057010104,465.8914,16.4274,4.2056,11.2869,3.5184,14.1803,...,17.2636,4.9406,16.3334,26.8672,1.0048,3.5458,18.9442,13.5570,17.3543,2021-08-17 16:06:44
496,20211007,5,11620525,1111056061002,180.1291,12.6887,8.1278,2.1684,23.3810,5.5894,...,9.7934,23.8109,10.2240,28.3686,9.9961,7.2371,5.7134,15.6473,6.1426,2021-08-17 16:06:44
497,20200819,20,11140635,1121078010101,540.8267,0.7004,14.3413,2.9791,0.2832,13.5837,...,0.0017,13.7260,14.1506,46.9632,10.5080,8.6825,3.9238,3.3179,13.5500,2021-08-17 16:06:44
498,20171011,11,11590605,1121082010004,992.2594,35.4771,8.4071,17.8773,1.2632,1.8164,...,3.9551,28.8403,10.7913,33.7729,1.4717,8.7947,8.5835,9.3403,0.0000,2021-08-17 16:06:44
499,20200725,21,11350625,1115053030001,1098.0798,12.6300,12.6652,18.6522,275.4479,20.0665,...,63.2687,18.9043,36.0630,27.1679,18.4721,13.1369,21.8967,6.0132,4.8362,2021-08-17 16:06:44

**index** 

인덱스는 책의 목차같은 개념

더 빠르게 검색하고, 데이터를 정렬할 때 사용되는 개념

In [6]:
sample.index

RangeIndex(start=0, stop=500, step=1)

In [7]:
# import pandas as pd

# sample = pd.read_csv('내국인 생활인구.csv', encoding='cp949', index_col=0)
# sample

In [8]:
import pandas as pd

sample = sample.set_index("일자(stdr_de_id)")  # set_index 메서드를 사용해서 할 수 있다.
sample.head()

,시간(tmzon_pd_se),행정동코드(adstrd_code_se),집계구코드(oa_cd),생활인구합계(tot_lvpop_co),남자0~9세(male_f0t9_lvpop_co),남자10~14세(male_f10t14_lvpop_co),남자15~19세(male_f15t19_lvpop_co),남자20~24세(male_f20t24_lvpop_co),남자25~29세(male_f25t29_lvpop_co),남자30~34세(male_f30t34_lvpop_co),...,여자40~44세(female_f40t44_lvpop_co),여자45~49세(female_f45t49_lvpop_co),여자50~54세(female_f50t54_lvpop_co),여자55~59세(female_f55t59_lvpop_co),여자60~64세(female_f60t64_lvpop_co),여자65~69세(female_f65t69_lvpop_co),여자70~74세(female_f70t74_lvpop_co),여자75~79세(female_f75t79_lvpop_co),여자80세이상(female_above_80_lvpop_co),등록일자(ldadng_dt)
일자(stdr_de_id),,,,,,,,,,,,,,,,,,,,,
20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,13.4910,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,8.4651,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,1.2299,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,27.6958,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,115.6026,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44

In [9]:
sample.index

Index([20170226, 20180107, 20180317, 20190222, 20210706, 20170801, 20190502,
       20170408, 20200614, 20201222,
       ...
       20190817, 20190426, 20170214, 20191123, 20190130, 20170603, 20211007,
       20200819, 20171011, 20200725],
      dtype='int64', name='일자(stdr_de_id)', length=500)

In [10]:
sample.columns

Index(['시간(tmzon_pd_se)', '행정동코드(adstrd_code_se)', '집계구코드(oa_cd)',
       '생활인구합계(tot_lvpop_co)', '남자0~9세(male_f0t9_lvpop_co)',
       '남자10~14세(male_f10t14_lvpop_co)', '남자15~19세(male_f15t19_lvpop_co)',
       '남자20~24세(male_f20t24_lvpop_co)', '남자25~29세(male_f25t29_lvpop_co)',
       '남자30~34세(male_f30t34_lvpop_co)', '남자35~39세(male_f35t39_lvpop_co)',
       '남자40~44세(male_f40t44_lvpop_co)', '남자45~49세(male_f45t49_lvpop_co)',
       '남자50~54세(male_f50t54_lvpop_co)', '남자55~59세(male_f55t59_lvpop_co)',
       '남자60~64세(male_f60t64_lvpop_co)', '남자65~69세(male_f65t69_lvpop_co)',
       '남자70~74세(male_f70t74_lvpop_co)', '남자75~79세(male_f75t79_lvpop_co)',
       '남자80세이상(male_above_80_lvpop_co)', '여자0~9세(female_f0t9_lvpop_co)',
       '여자10~14세(female_f10t14_lvpop_co)', '여자15~19세(female_f15t19_lvpop_co)',
       '여자20~24세(female_f20t24_lvpop_co)', '여자25~29세(female_f25t29_lvpop_co)',
       '여자30~34세(female_f30t34_lvpop_co)', '여자35~39세(female_f35t39_lvpop_co)',
       '여자40~44세(female_f40t44_lvpop_co)', '여자45~49세(female_f45t49_lvpop_co)',
       '여자50~54세(female_f50t54_lvpop_co)', '여자55~59세(female_f55t59_lvpop_co)',
       '여자60~64세(female_f60t64_lvpop_co)', '여자65~69세(female_f65t69_lvpop_co)',
       '여자70~74세(female_f70t74_lvpop_co)', '여자75~79세(female_f75t79_lvpop_co)',
       '여자80세이상(female_above_80_lvpop_co)', '등록일자(ldadng_dt)'],
      dtype='object')