# apply 함수
데이터 프레임에 파이썬 함수를 적용할 수 있다.

예를 들어, 가로, 세로, 높이를 이용해 부피라는 컬럼을 추가해보자

In [1]:
import pandas as pd

df = pd.DataFrame(
    {
        "가로": [10, 20, 30, 10, 30, 20, 11],
        "세로": [20, 23, 22, 33, 22, 12, 11],
        "높이": [50, 40, 20, 50, 20, 30, 40],
    }
)

df

   가로  세로  높이
0  10  20  50
1  20  23  40
2  30  22  20
3  10  33  50
4  30  22  20
5  20  12  30
6  11  11  40

In [2]:
# 인자는 row
def getVolume(row):
    return row.가로 * row.세로 * row.높이


df["부피"] = df.apply(getVolume, axis=1)
df

   가로  세로  높이     부피
0  10  20  50  10000
1  20  23  40  18400
2  30  22  20  13200
3  10  33  50  16500
4  30  22  20  13200
5  20  12  30   7200
6  11  11  40   4840